name: Dump

on:
  workflow_dispatch:
    inputs:
      LINK: 
        description: 'firmware link'
        required: true
        default: ''
      Part: 
        description: 'Partition (boot/system/recovery/...)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Dump
         run: |
              sudo apt update && sudo apt install git wget make p7zip-full p7zip-rar -y
              mkdir fw && cd fw && wget -c ${{ github.event.inputs.LINK }}
              7za -y x *
              7za -y x "*.tar*"
              zip output.zip ${{ github.event.inputs.PART }}*

       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: output.zip
            path: /home/runner/work/my_tools/my_tools/fw/output.zip
            retention-days: 4
